#!/bin/bash
DB=ssh-conf.db
touch $DB
sqlite3 $DB "CREATE TABLE 'Hosts'(
ID INT PRIMARY KEY NOT NULL,
HOSTNAME TEXT NOT NULL,
ADDRESS CHAR(15),
USERNAME TEXT NOT NULL,
KEY INT NOT NULL,
PORT INTEGER
);"
sqlite3 $DB "CREATE TABLE 'KEYS'(
KEYID INT PRIMARY KEY NOT NULL,
KEYNAME TEXT NOT NULL,
KEYPATH TEXT NOT NULL
);"

sqlite3 $DB "CREATE TABLE 'ADDITIONALPARAMS'(
KEYID INT NOT NULL,
PARAMETR TEXT NOT NULL,
VALUE TEXT
);"
